# Generated by Django 3.0.8 on 2020-07-17 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_retirada', models.IntegerField(verbose_name='Quantidade retirada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle.Produto')),
            ],
        ),
    ]
